In [1]:
import pandas as pd
import numpy as np
import os

# ADL path 전부 불러오기

In [2]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']


subject_list = ['SA01', 'SA02', 'SA03', 'SA04', 'SA05',
                'SA06', 'SA07', 'SA08', 'SA09', 'SA10',
                'SA11', 'SA12', 'SA13', 'SA14', 'SA15',
                'SA16', 'SA17', 'SA18', 'SA19', 'SA20',
                'SA21', 'SA22', 'SA23',
                'SE01', 'SE02', 'SE03', 'SE04', 'SE05',
                'SE06', 'SE07', 'SE08', 'SE09', 'SE10',
                'SE11', 'SE12', 'SE13', 'SE14', 'SE15']


total_adl_path = []

for path in paths:
    for subject_name in subject_list:
        path_rename = path.replace('SA01', subject_name)
        total_adl_path.append(path_rename)

total_adl_path

['../Dataset/SA01/D01_SA01_R01.csv',
 '../Dataset/SA02/D01_SA02_R01.csv',
 '../Dataset/SA03/D01_SA03_R01.csv',
 '../Dataset/SA04/D01_SA04_R01.csv',
 '../Dataset/SA05/D01_SA05_R01.csv',
 '../Dataset/SA06/D01_SA06_R01.csv',
 '../Dataset/SA07/D01_SA07_R01.csv',
 '../Dataset/SA08/D01_SA08_R01.csv',
 '../Dataset/SA09/D01_SA09_R01.csv',
 '../Dataset/SA10/D01_SA10_R01.csv',
 '../Dataset/SA11/D01_SA11_R01.csv',
 '../Dataset/SA12/D01_SA12_R01.csv',
 '../Dataset/SA13/D01_SA13_R01.csv',
 '../Dataset/SA14/D01_SA14_R01.csv',
 '../Dataset/SA15/D01_SA15_R01.csv',
 '../Dataset/SA16/D01_SA16_R01.csv',
 '../Dataset/SA17/D01_SA17_R01.csv',
 '../Dataset/SA18/D01_SA18_R01.csv',
 '../Dataset/SA19/D01_SA19_R01.csv',
 '../Dataset/SA20/D01_SA20_R01.csv',
 '../Dataset/SA21/D01_SA21_R01.csv',
 '../Dataset/SA22/D01_SA22_R01.csv',
 '../Dataset/SA23/D01_SA23_R01.csv',
 '../Dataset/SE01/D01_SE01_R01.csv',
 '../Dataset/SE02/D01_SE02_R01.csv',
 '../Dataset/SE03/D01_SE03_R01.csv',
 '../Dataset/SE04/D01_SE04_R01.csv',
 

In [3]:
adl_list = []

for path in total_adl_path:
    try:
        data = pd.read_csv(path, header=None)
        
        sliced_df = data[0 : 160]

        abs_df = np.absolute(sliced_df)
        adl_list.append(abs_df)
        
    except:
        pass


adl_array = np.asarray(adl_list)
adl_array = np.insert(adl_array, 160, 0, axis = 1)
print(np.asarray(adl_array))
print(adl_array.shape)

# 라벨은 따로 쓰기 (마지막 컬럼 )

[[[  45  337   39 ...  174 1308   38]
  [  49  334   44 ...  190 1304   70]
  [  48  330   54 ...  189 1294   96]
  ...
  [  32  268  114 ...  129 1038  340]
  [  24  272  118 ...  127 1041  333]
  [   0    0    0 ...    0    0    0]]

 [[  44  241   40 ...  167  986  190]
  [  42  242   40 ...  163  991  189]
  [  37  241   40 ...  150  997  192]
  ...
  [  15  188   20 ...   60  764   91]
  [  17  188   17 ...   60  788   85]
  [   0    0    0 ...    0    0    0]]

 [[  28  255   75 ...   35  980  150]
  [  31  255   82 ...   34  975  145]
  [  32  256   77 ...   36  973  149]
  ...
  [  26  217   34 ...   15  826   28]
  [  28  214   38 ...   21  829   21]
  [   0    0    0 ...    0    0    0]]

 ...

 [[   2  249   70 ...   39  952  217]
  [   5  248   68 ...   47  954  212]
  [   4  248   71 ...   43  950  214]
  ...
  [   2  249   69 ...   37  965  215]
  [   3  250   69 ...   37  964  215]
  [   0    0    0 ...    0    0    0]]

 [[   3  257   14 ...   18  991    6]
  [   3  254

In [4]:
np.save('adl_array', adl_array)

In [5]:
data_load = np.load('adl_array.npy')

data_load.shape

(2940, 161, 9)

# Fall path 전부 불러오기!

In [6]:
fall_list = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA01/F01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            fall_list.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            fall_list.append(tmp)
            
print(fall_list)

subject_list = ['SA01', 'SA02', 'SA03', 'SA04', 'SA05',
                'SA06', 'SA07', 'SA08', 'SA09', 'SA10',
                'SA11', 'SA12', 'SA13', 'SA14', 'SA15',
                'SA16', 'SA17', 'SA18', 'SA19', 'SA20',
                'SA21', 'SA22', 'SA23', 'SE06']

total_fall_path = []

for path in fall_list:
    for subject_name in subject_list:
        path_rename = path.replace('SA01', subject_name)
        total_fall_path.append(path_rename)

total_fall_path

['../Dataset/SA01/F01_SA01_R01.csv', '../Dataset/SA01/F01_SA01_R02.csv', '../Dataset/SA01/F01_SA01_R03.csv', '../Dataset/SA01/F01_SA01_R04.csv', '../Dataset/SA01/F01_SA01_R05.csv', '../Dataset/SA01/F02_SA01_R01.csv', '../Dataset/SA01/F02_SA01_R02.csv', '../Dataset/SA01/F02_SA01_R03.csv', '../Dataset/SA01/F02_SA01_R04.csv', '../Dataset/SA01/F02_SA01_R05.csv', '../Dataset/SA01/F03_SA01_R01.csv', '../Dataset/SA01/F03_SA01_R02.csv', '../Dataset/SA01/F03_SA01_R03.csv', '../Dataset/SA01/F03_SA01_R04.csv', '../Dataset/SA01/F03_SA01_R05.csv', '../Dataset/SA01/F04_SA01_R01.csv', '../Dataset/SA01/F04_SA01_R02.csv', '../Dataset/SA01/F04_SA01_R03.csv', '../Dataset/SA01/F04_SA01_R04.csv', '../Dataset/SA01/F04_SA01_R05.csv', '../Dataset/SA01/F05_SA01_R01.csv', '../Dataset/SA01/F05_SA01_R02.csv', '../Dataset/SA01/F05_SA01_R03.csv', '../Dataset/SA01/F05_SA01_R04.csv', '../Dataset/SA01/F05_SA01_R05.csv', '../Dataset/SA01/F06_SA01_R01.csv', '../Dataset/SA01/F06_SA01_R02.csv', '../Dataset/SA01/F06_SA01_R

['../Dataset/SA01/F01_SA01_R01.csv',
 '../Dataset/SA02/F01_SA02_R01.csv',
 '../Dataset/SA03/F01_SA03_R01.csv',
 '../Dataset/SA04/F01_SA04_R01.csv',
 '../Dataset/SA05/F01_SA05_R01.csv',
 '../Dataset/SA06/F01_SA06_R01.csv',
 '../Dataset/SA07/F01_SA07_R01.csv',
 '../Dataset/SA08/F01_SA08_R01.csv',
 '../Dataset/SA09/F01_SA09_R01.csv',
 '../Dataset/SA10/F01_SA10_R01.csv',
 '../Dataset/SA11/F01_SA11_R01.csv',
 '../Dataset/SA12/F01_SA12_R01.csv',
 '../Dataset/SA13/F01_SA13_R01.csv',
 '../Dataset/SA14/F01_SA14_R01.csv',
 '../Dataset/SA15/F01_SA15_R01.csv',
 '../Dataset/SA16/F01_SA16_R01.csv',
 '../Dataset/SA17/F01_SA17_R01.csv',
 '../Dataset/SA18/F01_SA18_R01.csv',
 '../Dataset/SA19/F01_SA19_R01.csv',
 '../Dataset/SA20/F01_SA20_R01.csv',
 '../Dataset/SA21/F01_SA21_R01.csv',
 '../Dataset/SA22/F01_SA22_R01.csv',
 '../Dataset/SA23/F01_SA23_R01.csv',
 '../Dataset/SE06/F01_SE06_R01.csv',
 '../Dataset/SA01/F01_SA01_R02.csv',
 '../Dataset/SA02/F01_SA02_R02.csv',
 '../Dataset/SA03/F01_SA03_R02.csv',
 

In [18]:
fall_list = []

for path in total_fall_path:
    try:
        data = pd.read_csv(path, header=None)
        last_col = data[8]
        last_col = list(last_col)
        last_col = int(last_col[-1].replace(';', ''))
        data[8] = last_col
        abs_data = np.absolute(data)
        abs_data = np.asarray(abs_data)
        
        max_value1 = abs_data[1000:][1].max()
        max_value2 = abs_data[1000:][2].max()
        max_value3 = abs_data[1000:][3].max()
        max_value4 = abs_data[1000:][4].max()
        max_value5 = abs_data[1000:][5].max()
        max_value6 = abs_data[1000:][6].max()
        max_value7 = abs_data[1000:][7].max()
        max_value8 = abs_data[1000:][8].max()
        max_value9 = abs_data[1000:][9].max()
        
        max_idx1 = abs_data[ max_value1 ][0]
        max_idx2 = abs_data[ max_value2 ][0]
        max_idx3 = abs_data[ max_value3 ][0]
        max_idx4 = abs_data[ max_value4 ][0]
        max_idx5 = abs_data[ max_value5 ][0]
        max_idx6 = abs_data[ max_value6 ][0]
        max_idx7 = abs_data[ max_value7 ][0]
        max_idx8 = abs_data[ max_value8 ][0]
        max_idx9 = abs_data[ max_value9 ][0]
        
        # print(max_idx1, max_idx2, max_idx3,
        #       max_idx4, max_idx5, max_idx6,
        #       max_idx7, max_idx8, max_idx9)
        
        min_idx = min(max_idx1, max_idx2, max_idx3,
                      max_idx4, max_idx5, max_idx6,
                      max_idx7, max_idx8, max_idx9)
        
        sliced_df = abs_data[min_idx - 200 : min_idx - 40]
        abs_df = np.absolute(sliced_df)
        # three_abs_df = abs_df.reshape(1, 160, 9)
        fall_list.append(abs_df)
        
    except:
        pass

base = fall_list[0]
base = base[np.newaxis, :]
print(base.shape)
print(base)

for i in range(1, 10):
    temp = fall_list[i][np.newaxis,:]
    print(temp.shape)
    base = np.concatenate([base,temp], axis=0)
    # print(base)

# print(base.shape)

# fall_array = np.insert(fall_array, 1)
# print(fall_array.shape)
# fall_array = np.insert(fall_array, 160, 0, axis = 1)
# print(np.asarray(fall_array))
# print(fall_array.shape)

# null 데이터 제거 후 3d array 시도 해보고 알려드리기

# mean-max scale (센서 특성 고려해서)
# label은 따로 column 처리해서 (model 돌리기 전에)

(1, 160, 9)
[[[120  69 252 ... 551 293 823]
  [118  67 250 ... 539 293 823]
  [121  73 243 ... 543 293 823]
  ...
  [117  68 252 ... 542 294 823]
  [117  68 249 ... 548 294 823]
  [119  71 252 ... 547 297 823]]]
(1, 160, 9)
(1, 0, 9)
(1, 0, 9)
(1, 160, 9)
(1, 160, 9)
(1, 160, 9)
(1, 160, 9)
(1, 160, 9)
(1, 160, 9)


In [ ]:
abs_df = np.concatenate(abs_df)
print(abs_df.shape)

(1440,)


In [138]:
max_idx2 = abs_data[max_value2][0]
max_idx2

11

In [ ]:
final_fall = pd.DataFrame(fall_array)
final_fall.to_csv('test_fall.csv', index=False)

# Concat

In [28]:
fall = pd.read_csv('./1125_ADL.csv')
adl = pd.read_csv('./1125_fall.csv')

fall_data = pd.DataFrame(fall)
print(fall_data.shape)
adl_data = pd.DataFrame(adl)
print(adl_data.shape)

file_list = [fall_data, adl_data]
result = pd.concat(file_list)
result.to_csv('test_all.csv', index=False)
print(result.shape)
result

(3209, 161)
(1799, 161)
(5008, 161)


0      1      2      3      4      5      6      7      8      9  \
0     205.0  196.0  194.0  196.0  202.0  236.0  250.0  277.0  318.0  344.0   
1     257.0  257.0  258.0  255.0  251.0  250.0  251.0  248.0  247.0  248.0   
2     273.0  273.0  272.0  275.0  274.0  276.0  273.0  272.0  273.0  274.0   
3     258.0  261.0  259.0  260.0  262.0  264.0  266.0  267.0  268.0  274.0   
4     252.0  247.0  249.0  249.0  245.0  245.0  250.0  248.0  244.0  242.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1794  253.0  253.0  256.0  257.0  256.0  254.0  258.0  252.0  255.0  254.0   
1795  254.0  253.0  250.0  252.0  252.0  250.0  254.0  253.0  254.0  254.0   
1796  258.0  256.0  256.0  253.0  254.0  252.0  253.0  251.0  253.0  253.0   
1797    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1798  249.0  257.0  246.0  252.0  251.0  251.0  249.0  246.0  248.0  245.0   

      ...    151    152    153    154    155    156    157    158    159  \
0     ...  248.0  249.0  249.0  252.0  248.0  243.0  236.0  236.0  232.0   
1     ...  242.0  241.0  238.0  238.0  236.0  237.0  233.0  234.0  239.0   
2     ...  274.0  273.0  274.0  276.0  274.0  275.0  270.0  273.0  275.0   
3     ...  293.0  290.0  291.0  288.0  274.0  276.0  273.0  276.0  273.0   
4     ...  241.0  240.0  234.0  236.0  234.0  229.0  228.0  227.0  221.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1794  ...  196.0  188.0  186.0  185.0  186.0  180.0  183.0  180.0  178.0   
1795  ...  241.0  247.0  259.0  257.0  265.0  276.0  289.0  296.0  294.0   
1796  ...  188.0  203.0  218.0  232.0  245.0  254.0  258.0  258.0  253.0   
1797  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1798  ...  199.0  199.0  188.0  181.0  174.0  163.0  205.0  159.0  136.0   

      target  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
1794       1  
1795       1  
1796       1  
1797       1  
1798       1  

[5008 rows x 161 columns]