In [1]:
import numpy as np

In [2]:
# 2차원 행렬.
x1 = np.array([[1,2,3],[4,5,6]])
print(x1)
print('-'*20)
print(f'shape = {x1.shape}')

[[1 2 3]
 [4 5 6]]
--------------------
shape = (2, 3)


In [3]:
# 또다른 2차원 행렬.
x2 = np.array([[7,8,9],[10,11,12]])
print(x2)
print('-'*20)
print(f'shape = {x2.shape}')

[[ 7  8  9]
 [10 11 12]]
--------------------
shape = (2, 3)


In [4]:
# 또다른 2차원 행렬.
x3 = np.array([[13,14,15],[16,17,18]])
print(x3)
print('-'*20)
print(f'shape = {x3.shape}')

[[13 14 15]
 [16 17 18]]
--------------------
shape = (2, 3)


In [5]:
# 3차원 배열로 재구성.
x1 = x1[np.newaxis, :]
x2 = x2[np.newaxis, :]
x3 = x3[np.newaxis, :]

In [6]:
# 각각의 shape를 본다.
print(x1.shape)
print(x2.shape)
print(x3.shape)

(1, 2, 3)
(1, 2, 3)
(1, 2, 3)


In [7]:
# axis = 0 방향으로 이어 붙인다.
x_total = np.concatenate([x1,x2,x3], axis=0)
x_total

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
# 최종적으로 shape를 본다.
x_total.shape

(3, 2, 3)