In [5144]:
import numpy as np
import pandas as pd
from scipy.signal import butter, lfilter, freqz
import matplotlib.pyplot as plt

In [5145]:
df = pd.read_csv('C:/Users/kss29/Desktop/sisfall data/SisFalldataset_modify/SisFalldataset_modify/SA14/F03_SA14_R01.csv',header = None)

In [5146]:
df.head()

0    1  2   3   4   5   6     7    8
0  6 -264  3 -58  54 -11  17 -1013  106
1  7 -267  0 -59  54 -14  17 -1013  106
2  6 -264  0 -59  52 -14  18 -1007  103
3  6 -262  2 -61  49 -16  12 -1005  105
4  5 -262  2 -61  45 -17  12 -1003  113

In [5147]:
columns = df.columns

In [5148]:
print(df.columns)

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')


In [5149]:
sis_data = list()
for i in columns:
    sis_data.append(df[i].to_numpy())

In [5150]:
div_100 = list()
for i in sis_data:
     div_100.append(i /100)

In [5151]:
div_100

[array([ 0.06,  0.07,  0.06, ..., -2.58, -2.61, -2.58]),
 array([-2.64, -2.67, -2.64, ..., -0.08, -0.07, -0.07]),
 array([ 0.03,  0.  ,  0.  , ..., -0.61, -0.61, -0.61]),
 array([-0.58, -0.59, -0.59, ..., -0.03, -0.04, -0.02]),
 array([0.54, 0.54, 0.52, ..., 0.54, 0.54, 0.54]),
 array([-0.11, -0.14, -0.14, ...,  0.  , -0.01,  0.  ]),
 array([ 0.17,  0.17,  0.18, ..., -9.93, -9.93, -9.93]),
 array([-10.13, -10.13, -10.07, ...,  -0.14,  -0.1 ,  -0.12]),
 array([ 1.06,  1.06,  1.03, ..., -1.54, -1.55, -1.53])]

In [5152]:
import math

In [5153]:
def butter_lowpass(cutoff, fs, order=4):
    nyq = 0.5 * fs
    normal_cutoff = cutoff / nyq
    b, a = butter(order, normal_cutoff, btype='low', analog=False)
    return b, a

def butter_lowpass_filter(data, cutoff, fs, order=4):
    b, a = butter_lowpass(cutoff, fs, order=order)
    x = np.trunc(np.array(data, dtype=np.float64)).astype(np.int64)
    y = lfilter(b, a, x, axis=-1, zi=None)
    return y

# Setting standard filter requirements.
order = 4
fs = 200
cutoff = 5

b, a = butter_lowpass(cutoff, fs, order)

# Creating the data for filteration
T = 200         # value taken in seconds
n = int(T * fs) # indicates total samples
t = np.linspace(0, T, n, endpoint=False)

In [5154]:
for k, value in enumerate(div_100,1):
    globals()['y_{}'.format(k)] = butter_lowpass_filter(value, cutoff, fs, order)

In [5155]:
new_data = []
data_int = [y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9]

for i in data_int: 
    new = i.astype(int)
    new_data.append(new)

In [5156]:
new_data

[array([ 0,  0,  0, ..., -1, -1, -1]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([ 0,  0,  0, ..., -9, -9, -9]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [5157]:
df_new = pd.DataFrame(new_data)
df_new = df_new.transpose()
df_new.to_csv('C:/Users/kss29/Data_handling/study/LPF/FALL/F03_SA14_R01_LPF.csv')